<?php

/**
 * @file
 *
 * Handles the creation/display of islandora:sp-remote_resource objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_remote_resource_menu() {
  return array(
    'admin/islandora/remote_resource' => array(
      'title' => 'Remote Resource Module',
      'description' => 'Configure the remote resource solution pack.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_remote_resource_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    )
  );
}

/**
 * Implements hook_theme().
 */
function islandora_remote_resource_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_remote_resource' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-remote-resource',
      'pattern' => 'islandora_remote_resource__',
      'variables' => array('islandora_object' => NULL),
    )
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_remote_resource_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_remote_resource');
  // remote_resource Content Model
  $remote_resource_content_model = $connection->repository->constructObject('islandora:sp_remote_resource');
  $remote_resource_content_model->owner = 'fedoraAdmin';
  $remote_resource_content_model->label = 'Islandora Remote Resource Content Model';
  $remote_resource_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream
  $datastream = $remote_resource_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_remote_resource_ds_composite_model.xml", FALSE);
  $remote_resource_content_model->ingestDatastream($datastream);
  // Remote Resource Collection
  $remote_resource_collection = $connection->repository->constructObject('islandora:sp_remote_resource_collection');
  $remote_resource_collection->owner = 'fedoraAdmin';
  $remote_resource_collection->label = 'Remote Resource Collection';
  $remote_resource_collection->models = 'islandora:collectionCModel';
  $remote_resource_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream
  $datastream = $remote_resource_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_remote_resource_collection_policy.xml", FALSE);
  $remote_resource_collection->ingestDatastream($datastream);
  // TN Datastream
  $datastream = $remote_resource_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $remote_resource_collection->ingestDatastream($datastream);
  return array(
    'islandora_remote_resource' => array(
      'title' => 'Islandora Remote Resource',
      'objects' => array(
        $remote_resource_content_model,
        $remote_resource_collection
      )
    )
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_remote_resource_islandora_sp_remote_resource_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_remote_resource', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */

function islandora_remote_resource_islandora_sp_remote_resource_islandora_object_ingested($object) {
  module_load_include('inc', 'islandora_remote_resource', 'includes/derivatives');
  islandora_remote_resource_create_all_derivatives($object);
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_remote_resource_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_remote_resource');
  return array(
    'Remote Resource MODS form' => array(
      'form_file' => "$module_path/xml/islandora_remote_resource_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_remote_resource_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_remote_resource_mods_form' => array(
      'content_model' => 'islandora:sp_remote_resource',
      'form_name' => 'Remote Resource MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_remote_resource_islandora_sp_remote_resource_islandora_ingest_steps(array $configuration) {
  return array(
    'islandora_remote_resource_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_remote_resource_remote_resource_form',
      'module' => 'islandora_remote_resource',
      'file' => 'includes/remote_resource.form.inc'
    )
  );
}
